name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder:
          - resource_group
          - virtual_network
          - subnet
          - virtual_machine

    defaults:
      run:
        working-directory: ${{ matrix.folder }}

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init

      - run: terraform plan

      - run: terraform apply -auto-approve